import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App - kdt01",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>       

        <div className="min-h-screen flex flex-col bg-cover bg-center bg-no-repeat bg-sky-50">
        
        {/* 상단 바 */}
        <header id="headcolor" className="w-full px-4 py-4 shadow-sm">
          <Nav />
        </header>
      
        {/* 메인 화면 */}
        <main id="maincolor" className="flex-1 w-full flex flex-col items-center justify-start px-4 py-6">
          {children}
        </main>
        
        {/* 하단 바 */}
        <Footer />
        
      </div>
      </body>
    </html>
  );
}
